default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: challenge_2_dev

test:
  <<: *default
  database: challenge_2_test

production:
  <<: *default
  database: challenge_2_prod
